// GENERATED by scripts/bake-surfaces.mjs — do not edit by hand.
export const SURFACE_NAMES = ["festival-poster","trail-sign","woodland-welcome-board"] as const;
export const CUTOUT_NAMES = ["star-cutout"] as const;
